apiVersion: v1
kind: Service
metadata:
  name: harald
  namespace: selfservice-herald-vbqkr
  labels:
    app: harald
    project: selfservice
    department: devex
    component: harald
    scrape-service-metrics: "true"
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    app: harald